# Application Name
spring.application.name=Course_Registration_System

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/CourseDB
spring.datasource.username=root
spring.datasource.password=JAGA

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port (Optional)
#server.port=8080